const AdminRouter = require("express").Router();
const uploadRouter = require("../utils/upload");
const userRouter = require("./Admin/user.routes");
const permissionRouter = require("./Admin/permission.routes");
const roleRouter = require("./Admin/role.routes");
const departmentRouter = require("./Admin/department.routes");
const designationRouter = require("./Admin/designation.routes");
const supplierRouter = require("./Admin/supplier.routes");
const vendorRouter = require("./Admin/vendor.routes");
const clientRouter = require("./Admin/client.routes");
const productRouter = require("./Admin/product.routes");
const machineRouter = require("./Admin/machine.routes");
const orderReceivedRouter = require("./Admin/orderReceived.routes");
const orderModeRouter = require("./Admin/orderMode.routes");
const paperType = require("./Admin/paperType.routes");
const categoryRouter = require("./Admin/category.routes");
const paperRouter = require("./Admin/paper.routes");
const inkAndChemicalRouter = require("./Admin/inkAndChemical.routes");
const offsetDieRouter = require("./Admin/offsetDie.routes");
const embossBlockRouter = require("./Admin/embossBlock.routes");
const foilsBlockRouter = require("./Admin/foilsBlock.routes");
const coatingRouter = require("./Admin/coating.routes");
const laminationRouter = require("./Admin/lamination.routes");
const pestingRouter = require("./Admin/pesting.routes");
const salesOrderBookingRouter = require("./Admin/salesOrderBooking.routes");
const bindingRouter = require("./Admin/binding.routes");
const artWorkRouter = require("./Admin/artWork.routes");
const jobSheetPreparationRouter = require("./Admin/jobSheetPreparation.routes");
const foilsRoutes = require("./Admin/foils.routes");
const embossRouter = require("./Admin/emboss.routes");
const DieDrawingRouter = require("./Admin/dieDrawing.routes");
const PrintingPlateRouter = require("./Admin/printingPlate.routes");
const CoatingPlateRouter = require("./Admin/coatingPlate.routes");
const JobCardGenerateRouter = require("./Admin/jobCardGenerate.routes");
const reportOrderReceived = require("./Admin/report.OrderReceived.routes");
const reportsalesOrderBooking = require("./Admin/report.salesOrderBooking.routes");
const reportartworkRouter = require("./Admin/report.artwork.routes");
const reportFoilsRouter = require("./Admin/report.foils.routes");
const reportEmbossRoutes = require("./Admin/report.emboss.routes");
const reportDieDrawingRouter = require("./Admin/report.dieDrawing.routes");
const reportPrintingPlateRouter = require("./Admin/report.printingPlate.routes");
const reportCoatingPlateRouter = require("./Admin/report.cotingPlate.routes");
const reportjobsheetRoutes = require("./Admin/report.jobSheetPreparation.routes");
const DeleteRouter = require("./Admin/delete-logs.routes");

AdminRouter.use("/user", userRouter);
AdminRouter.use("/upload", uploadRouter);
AdminRouter.use("/permission", permissionRouter);
AdminRouter.use("/role", roleRouter);
AdminRouter.use("/department", departmentRouter);
AdminRouter.use("/designation", designationRouter);
AdminRouter.use("/supplier", supplierRouter);
AdminRouter.use("/vendor", vendorRouter);
AdminRouter.use("/client", clientRouter);
AdminRouter.use("/product", productRouter);
AdminRouter.use("/machine", machineRouter);
AdminRouter.use("/order-received", orderReceivedRouter);
AdminRouter.use("/orderMode", orderModeRouter);
AdminRouter.use("/paperType", paperType);
AdminRouter.use("/category", categoryRouter);
AdminRouter.use("/paper", paperRouter);
AdminRouter.use("/ink-and-chemical", inkAndChemicalRouter);
AdminRouter.use("/offset-die", offsetDieRouter);
AdminRouter.use("/emboss-block", embossBlockRouter);
AdminRouter.use("/foils-block", foilsBlockRouter);
AdminRouter.use("/coating", coatingRouter);
AdminRouter.use("/lamination", laminationRouter);
AdminRouter.use("/pesting", pestingRouter);
AdminRouter.use("/sales-order-booking", salesOrderBookingRouter);
AdminRouter.use("/binding", bindingRouter);
AdminRouter.use("/art-work", artWorkRouter);
AdminRouter.use("/job-sheet-preparation", jobSheetPreparationRouter);
AdminRouter.use("/foils", foilsRoutes);
AdminRouter.use("/emboss", embossRouter);
AdminRouter.use("/die-drawing", DieDrawingRouter);
AdminRouter.use("/printing-plate", PrintingPlateRouter);
AdminRouter.use("/coating-plate", CoatingPlateRouter);
AdminRouter.use("/Job-Card-Generate", JobCardGenerateRouter);
AdminRouter.use("/order-Recevies-download", reportOrderReceived);
AdminRouter.use("/salesOrder-booking-report", reportsalesOrderBooking);
AdminRouter.use("/report-artwork", reportartworkRouter);
AdminRouter.use("/report-foils", reportFoilsRouter);
AdminRouter.use("/report-emboss", reportEmbossRoutes);
AdminRouter.use("/report-die-drawing", reportDieDrawingRouter);
AdminRouter.use("/report-printingPlate", reportPrintingPlateRouter);
AdminRouter.use("/report-coating-plate", reportCoatingPlateRouter);
AdminRouter.use("/report-jobsheet", reportjobsheetRoutes);
AdminRouter.use("/delete-logs", DeleteRouter);

module.exports = AdminRouter;
